"""Cold-start anti-sameness ledger (F1).

Defends against atelier's own KB + anti-slop rules converging into a recognizable
"atelier style" — the next monoculture, generated by the anti-monoculture tool. For
greenfield work with NO repo to measure, fingerprint each output (palette centroid +
display font + layout archetype) and warn when a new one is materially the same as a
recent one, so the next project picks a different direction. Scoped strictly to cold
start; NEVER overrides a measured repo's contract.

    python3 cold_start_ledger.py record <font> <archetype> <#hex> [<#hex> ...]
    python3 cold_start_ledger.py check  <font> <archetype> <#hex> [<#hex> ...] [--category <cat>]

There are TWO orthogonal anti-sameness defenses:
  • recent-collision  — the proposed look is materially the same as one of atelier's
    OWN recent cold-start outputs (the tool converging on itself);
  • category reflex-reject — the proposed look is the predictable "safe" choice for
    its product CATEGORY even on the very first output (the second-order trap). This
    is opt-in via `--category`; with no category it never fires and behavior is
    byte-identical to the recent-collision-only ledger.
"""
import json
import os
import re
import sys

from scan_repo import _hex_to_rgb, _delta_e

DEFAULT_LEDGER = os.environ.get("ATELIER_LEDGER") or os.path.expanduser("~/.atelier/cold-start.jsonl")
DELTA_E = 12.0   # mean nearest-neighbor ΔE between palettes below this (same font+archetype) = "same look"
RECENT = 5       # only compare against the last N cold-start outputs
REFLEX_DELTA_E = 12.0   # palette hue within this ΔE of a category's reflex anchor = "the safe pick"
REFLEX_CSV = os.path.join(
    os.path.dirname(__file__), "..", "references", "knowledge", "reflex-reject.csv")


def _norm_font(font):
    # first family, lowercased, quotes + fallback stack stripped ("Sora, sans-serif" -> "sora")
    return (font or "").split(",")[0].strip().strip("'\"").lower()


def _palette_rgbs(palette):
    out = []
    for h in palette or []:
        if isinstance(h, str) and h.startswith("#"):
            try:
                out.append(_hex_to_rgb(h))
            except Exception:
                pass
    return out


def _palette_distance(a, b):
    """Symmetric mean nearest-neighbor ΔE between two color SETS — robust to palette
    length (padding with a neutral can't evade) and to a shared centroid of unlike
    colors (red+blue ≠ all-purple). Empty/non-hex palette -> infinite (never collides)."""
    ra, rb = _palette_rgbs(a), _palette_rgbs(b)
    if not ra or not rb:
        return float("inf")
    def avg_nn(xs, ys):
        return sum(min(_delta_e(x, y) for y in ys) for x in xs) / len(xs)
    return (avg_nn(ra, rb) + avg_nn(rb, ra)) / 2


def _rel_luminance(rgb):
    """WCAG relative luminance of an (r,g,b) 0-255 triple."""
    def lin(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = rgb
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


DARK_SURFACE = 0.08   # rel-luminance below this = a genuinely dark surface
LIGHT_SURFACE = 0.5   # rel-luminance above this = a genuinely light surface


def ground_side(palette):
    """Classify a palette's GROUND as 'dark' or 'light' — the single most perceptually
    dominant 'this looks different' axis (the eye reads value before hue or type). With no
    area weighting available (just a hex set), compare how many colors are genuinely DARK
    surfaces (<DARK_SURFACE) vs genuinely LIGHT surfaces (>LIGHT_SURFACE): a dark page
    stacks several dark surfaces (ground + raised surfaces + borders) and only a light ink
    or two, a light page is the reverse. Whichever extreme has MORE colors is the ground
    side; mid-tone accents (the trap for a naive mean/median, e.g. a navy page's indigo
    accents) are ignored. A tie breaks toward 'dark' only when the floor is near-black and
    there is no near-white ground. A heuristic, not a render measurement — the doctrine
    advisory it powers is non-gating. Returns 'dark'/'light', or None for an empty/non-hex
    palette (never collides)."""
    lums = [_rel_luminance(rgb) for rgb in _palette_rgbs(palette)]
    if not lums:
        return None
    dark = sum(1 for l in lums if l < DARK_SURFACE)
    light = sum(1 for l in lums if l > LIGHT_SURFACE)
    if dark == light:
        return "dark" if (min(lums) < 0.03 and max(lums) < 0.85) else "light"
    return "dark" if dark > light else "light"


def fingerprint(font, archetype, palette):
    return {
        "font": _norm_font(font),
        "archetype": (archetype or "").lower(),
        "palette": [h.lower() for h in palette if isinstance(h, str)],
        "ground": ground_side(palette),
    }


def load(ledger=DEFAULT_LEDGER):
    """Tolerant: a torn/half-written or malformed line never kills the gate."""
    if not os.path.exists(ledger):
        return []
    out = []
    for line in open(ledger, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
            if isinstance(row, dict):
                out.append(row)
        except Exception:
            pass
    return out


def record(fp, ledger=DEFAULT_LEDGER):
    os.makedirs(os.path.dirname(ledger) or ".", exist_ok=True)
    with open(ledger, "a", encoding="utf-8") as f:
        f.write(json.dumps(fp) + "\n")
    return fp


def same_ground_value(fp, ledger=DEFAULT_LEDGER, n=RECENT):
    """Return the most recent prior on the SAME ground value-side (both dark, or both
    light) as the proposed pick, or None. Value (light↔dark) is the FIRST thing the eye
    reads — diverging on hue/type/layout while keeping the same value reads as a reskin at
    a glance. Orthogonal to `too_similar` (which keys on same font+archetype): a stone-grey
    page and a navy page are far apart in ΔE yet both read 'dark'. Advisory, not a hard
    collision — a brief can legitimately need the same value as a prior; it's a prompt to
    consider flipping the value, which is the strongest single distinctness move."""
    side = fp.get("ground")
    if side is None:
        return None
    for prior in reversed(load(ledger)[-n:]):
        if prior.get("ground") == side:
            return prior
    return None


def too_similar(fp, ledger=DEFAULT_LEDGER, n=RECENT):
    """Return the most recent colliding fingerprint (same normalized font + archetype,
    palette sets within ΔE of a recent one), or None."""
    for prior in reversed(load(ledger)[-n:]):
        if prior.get("font") == fp["font"] and prior.get("archetype") == fp["archetype"]:
            if _palette_distance(fp.get("palette"), prior.get("palette")) <= DELTA_E:
                return prior
    return None


# --- category reflex-reject (the SECOND-order trap) --------------------------
# Orthogonal to recent-collision: even atelier's very FIRST output for a category
# can be the predictable "safe" choice for that category (every fintech →
# emerald/teal + Space Grotesk). reflex-reject.csv curates those per category; this
# warns when a proposed font is in the category's reflex font list OR any palette
# color sits within ΔE of a reflex hue anchor.
_HEX_IN = re.compile(r"#[0-9a-fA-F]{3,8}\b")


def _split_field(raw):
    """Split a reflex CSV multi-value field on ; or , into stripped tokens."""
    out = []
    for part in (raw or "").replace(";", ",").split(","):
        part = part.strip()
        if part:
            out.append(part)
    return out


def _norm_cat(c):
    return (c or "").strip().lower()


def load_reflex(csv_path=REFLEX_CSV):
    """Parse reflex-reject.csv -> {norm_category: {fonts:[...], styles:[...],
    hues:[(label,#hex)...], note:str}}. Tolerant: a missing/torn file yields {}."""
    import csv
    out = {}
    if not os.path.exists(csv_path):
        return out
    try:
        with open(csv_path, encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                cat = _norm_cat(row.get("category"))
                if not cat:
                    continue
                hues = []
                for tok in _split_field(row.get("reflex_palette_hues")):
                    m = _HEX_IN.search(tok)
                    if m:
                        label = tok[:m.start()].strip() or tok
                        hues.append((label, m.group(0)))
                out[cat] = {
                    "fonts": [_norm_font(f) for f in _split_field(row.get("reflex_fonts"))],
                    "styles": _split_field(row.get("reflex_styles")),
                    "hues": hues,
                    "note": (row.get("note") or "").strip(),
                    "reach_for": (row.get("reach_for") or "").strip(),
                }
    except Exception:
        return out
    return out


def reflex_reject_hit(font, palette, category, csv_path=REFLEX_CSV):
    """Return a structured warning if the proposed (font, palette) is the reflex
    "safe" choice for `category`, else None. Fires when the normalized font is in the
    category's reflex_fonts OR any palette color is within REFLEX_DELTA_E of a reflex
    hue anchor. Returns None on no match, an unknown category, or no category."""
    if not category:
        return None
    table = load_reflex(csv_path)
    row = table.get(_norm_cat(category))
    if not row:
        return None
    reasons = []
    nf = _norm_font(font)
    if nf and nf in row["fonts"]:
        reasons.append({"kind": "font", "matched": nf})
    # (rgb, hex) pairs from ONE filtered pass so the reported hex always corresponds to
    # the rgb that matched — a "#" string that fails to parse is skipped in both.
    pal_pairs = []
    for h in (palette or []):
        if isinstance(h, str) and h.startswith("#"):
            try:
                pal_pairs.append((_hex_to_rgb(h), h))
            except Exception:
                pass
    hue_hits = []
    for label, anchor in row["hues"]:
        try:
            a_rgb = _hex_to_rgb(anchor)
        except Exception:
            continue
        for prgb, phex in pal_pairs:
            if _delta_e(prgb, a_rgb) <= REFLEX_DELTA_E:
                hue_hits.append({"palette": phex, "anchor": anchor, "label": label})
                break
    if hue_hits:
        reasons.append({"kind": "palette", "hits": hue_hits})
    if not reasons:
        return None
    return {"category": _norm_cat(category), "reasons": reasons,
            "reflex_fonts": row["fonts"], "reflex_styles": row["styles"],
            "note": row["note"], "reach_for": row.get("reach_for", "")}


def _extract_category(argv):
    """Pull an optional trailing `--category <cat>` out of argv (no argparse, to match
    the file's positional style). Returns (category_or_None, argv_without_category)."""
    out, cat, i = [], None, 0
    while i < len(argv):
        tok = argv[i]
        if tok == "--category" and i + 1 < len(argv):
            cat = argv[i + 1]
            i += 2
            continue
        if tok.startswith("--category="):
            cat = tok.split("=", 1)[1]
            i += 1
            continue
        out.append(tok)
        i += 1
    return cat, out


if __name__ == "__main__":
    category, a = _extract_category(sys.argv[1:])
    if len(a) >= 4 and a[0] in ("record", "check"):
        fp = fingerprint(a[1], a[2], a[3:])
        if a[0] == "record":
            record(fp)
            print("recorded:", json.dumps(fp))
        else:
            fired = False
            hit = too_similar(fp)
            if hit:
                print("⚠ too similar to a recent cold-start output — pick a different direction:")
                print("  prior:", json.dumps(hit))
                fired = True
            reflex = reflex_reject_hit(a[1], a[3:], category)
            if reflex:
                print(f"⚠ this is the reflex 'safe' choice for category {reflex['category']!r} "
                      "— the second-order trap; push for a more specific direction:")
                print("  reasons:", json.dumps(reflex["reasons"]))
                if reflex["note"]:
                    print("  why:", reflex["note"])
                if reflex.get("reach_for"):
                    print("  reach for instead:", reflex["reach_for"])
                fired = True
            # value-axis advisory (NON-gating): value (light↔dark) is the first thing the
            # eye reads, so a same-value prior is a prompt to consider flipping it — the
            # strongest single at-a-glance distinctness move. Never changes the exit code.
            vhit = same_ground_value(fp)
            if vhit and fp.get("ground"):
                print(f"• note: this pick reads {fp['ground'].upper()} like a recent output "
                      f"({vhit.get('ground')} ground). Value is the FIRST thing the eye reads —"
                      f" diverging on hue/type/layout but keeping the same value can read as a "
                      f"reskin at a glance. If the brief allows, flipping the ground "
                      f"{'light' if fp['ground']=='dark' else 'dark'} is the strongest single "
                      f"distinctness move.")
            if fired:
                sys.exit(1)
            print("✓ distinct from recent cold-start outputs"
                  + (" and not the category reflex." if category else "."))
        sys.exit(0)
    print("usage: cold_start_ledger.py record|check <font> <archetype> <#hex> [<#hex> ...] "
          "[--category <cat>]")
    sys.exit(2)
