"""Cold-start anti-sameness ledger (F1).

Defends against atelier's own KB + anti-slop rules converging into a recognizable
"atelier style" — the next monoculture, generated by the anti-monoculture tool. For
greenfield work with NO repo to measure, fingerprint each output (palette centroid +
display font + layout archetype) and warn when a new one is materially the same as a
recent one, so the next project picks a different direction. Scoped strictly to cold
start; NEVER overrides a measured repo's contract.

    python3 cold_start_ledger.py record <font> <archetype> <#hex> [<#hex> ...]
    python3 cold_start_ledger.py check  <font> <archetype> <#hex> [<#hex> ...]
"""
import json
import os
import sys

from scan_repo import _hex_to_rgb, _delta_e, _rgb_to_hex

DEFAULT_LEDGER = os.path.expanduser("~/.atelier/cold-start.jsonl")
DELTA_E = 10.0   # same font+archetype AND palette centroid within this reads as "the same look"
RECENT = 5       # only compare against the last N cold-start outputs


def _centroid(palette):
    rgbs = [_hex_to_rgb(h) for h in palette if isinstance(h, str) and h.startswith("#")]
    if not rgbs:
        return (128, 128, 128)
    n = len(rgbs)
    return tuple(round(sum(c[i] for c in rgbs) / n) for i in range(3))


def fingerprint(font, archetype, palette):
    return {
        "font": (font or "").lower(),
        "archetype": (archetype or "").lower(),
        "palette": [h.lower() for h in palette],
        "centroid": _rgb_to_hex(*_centroid(palette)),
    }


def load(ledger=DEFAULT_LEDGER):
    if not os.path.exists(ledger):
        return []
    return [json.loads(l) for l in open(ledger, encoding="utf-8") if l.strip()]


def record(fp, ledger=DEFAULT_LEDGER):
    os.makedirs(os.path.dirname(ledger) or ".", exist_ok=True)
    with open(ledger, "a", encoding="utf-8") as f:
        f.write(json.dumps(fp) + "\n")
    return fp


def too_similar(fp, ledger=DEFAULT_LEDGER, n=RECENT):
    """Return the most recent colliding fingerprint (same font + archetype, palette
    centroid within ΔE of a recent one), or None."""
    c = _hex_to_rgb(fp["centroid"])
    for prior in reversed(load(ledger)[-n:]):
        if prior.get("font") == fp["font"] and prior.get("archetype") == fp["archetype"]:
            if _delta_e(c, _hex_to_rgb(prior["centroid"])) <= DELTA_E:
                return prior
    return None


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) >= 4 and a[0] in ("record", "check"):
        fp = fingerprint(a[1], a[2], a[3:])
        if a[0] == "record":
            record(fp)
            print("recorded:", json.dumps(fp))
        else:
            hit = too_similar(fp)
            if hit:
                print("⚠ too similar to a recent cold-start output — pick a different direction:")
                print("  prior:", json.dumps(hit))
                sys.exit(1)
            print("✓ distinct from recent cold-start outputs.")
        sys.exit(0)
    print("usage: cold_start_ledger.py record|check <font> <archetype> <#hex> [<#hex> ...]")
    sys.exit(2)
