"""Generate native theme code from the design tokens — real cross-platform handoff.

Beyond CSS/Tailwind/W3C-JSON, this emits the platform-idiomatic theme files so the
SAME contract drives SwiftUI, Flutter, and React Native — not just "export the JSON
and figure it out". The canonical source stays `design-tokens.json` / DESIGN.md.

Usage:
    python3 export_native.py <repo | design-tokens.json> [--out design/native]
"""
import os
import sys

from contract import resolve_contract
from scan_repo import _hex_to_rgb


def _pascal(name):
    return "".join(p.capitalize() for p in name.replace("-", " ").replace("_", " ").split())


def _camel(name):
    # Preserve an already-camelCase token (e.g. "onPrimary") rather than flattening it
    # via _pascal's per-word .capitalize() (which would yield "onprimary"). Only split
    # + recombine when the name carries an explicit separator.
    if name and not any(sep in name for sep in ("-", "_", " ")):
        return name[:1].lower() + name[1:]
    p = _pascal(name)
    return p[:1].lower() + p[1:] if p else name


def _swift_weight(w):
    """Map a numeric/string CSS font-weight to a SwiftUI `Font.Weight` case.
    Unknown/absent -> `.regular` (a real case, never a fabricated one)."""
    table = {"100": "ultraLight", "200": "thin", "300": "light", "400": "regular",
             "500": "medium", "600": "semibold", "700": "bold", "800": "heavy",
             "900": "black", "normal": "regular", "regular": "regular",
             "bold": "bold", "semibold": "semibold", "medium": "medium",
             "light": "light", "thin": "thin", "heavy": "heavy", "black": "black"}
    return table.get(str(w).strip().lower(), "regular")


def _num(v):
    """A CSS length/number token -> a Swift CGFloat literal string (strips a `px`/`pt`
    unit, keeps the number). Non-numeric -> None so the caller can skip it honestly."""
    if v is None:
        return None
    s = str(v).strip().lower()
    for unit in ("px", "pt", "rem", "em"):
        if s.endswith(unit):
            s = s[:-len(unit)].strip()
    try:
        f = float(s)
    except ValueError:
        return None
    return str(int(f)) if f == int(f) else f"{f:g}"


def swiftui(colors, fonts, dark=None, typography=None, spacing=None,
            radius=None, rounded=None, shadows=None):
    """Emit a complete, idiomatic SwiftUI theme from the contract.

    Produces ONE Swift file: a `Color(light:dark:)` dynamic-color initializer (correct
    scheme-aware pattern via `UIColor`/`NSColor` dynamic providers), a `Theme` value
    type with nested `colors`/`spacing`/`radius`/`typography` groups, an
    `EnvironmentKey` + `@Environment(\\.theme)` so views read `theme.colors.primary`,
    a `TextStyle` enum + `.textStyle(_:)` view modifier carrying size+weight+lineHeight,
    and a usage example. Every color role resolves per `ColorScheme`. Honest about the
    one thing SwiftUI can't express verbatim (the web box-shadow elevation string).

    `dark` is the dark-scheme {role: hex} map; when absent, each role falls back to its
    light value for both schemes (still a valid dynamic color, disclosed in the header).
    """
    dark = dark or {}
    typography = typography or {}
    rounded = rounded or {}

    def comp(hexv):
        r, g, b = _hex_to_rgb(hexv)
        return r / 255, g / 255, b / 255

    out = []
    out.append("import SwiftUI")
    out.append("")
    out.append("// Generated by atelier from the design contract. Do not edit by hand.")
    out.append("// Every color role resolves dynamically per ColorScheme (light/dark).")
    if colors and not dark:
        out.append("// NOTE: no dark palette in the contract — each role uses its light")
        out.append("//       value for both schemes (still a valid dynamic color).")
    if shadows:
        out.append("// NOTE: the web box-shadow elevation token has no 1:1 SwiftUI form;")
        out.append("//       it is surfaced as a `.shadow(color:radius:x:y:)` helper below,")
        out.append("//       approximating the CSS shadow (SwiftUI shadows are single-layer,")
        out.append("//       and a Gaussian `radius` is not the same primitive as a CSS blur).")
    if typography:
        out.append("// NOTE: SwiftUI has no precise total-line-height control — `.lineSpacing`")
        out.append("//       adds gap BETWEEN lines on top of the font's intrinsic leading. Each")
        out.append("//       style's `lineSpacing` (= token lineHeight − size) APPROXIMATES the")
        out.append("//       token line height; the exact token `lineHeight` is kept on the spec.")
    out.append("// NOT COMPILED in this environment — generated deterministically; verify in Xcode.")
    out.append("")

    # --- dynamic Color(light:dark:) — the correct scheme-aware idiom ----------
    out.append("public extension Color {")
    out.append("    /// A color that resolves to `light` in light mode and `dark` in dark mode.")
    out.append("    init(light: Color, dark: Color) {")
    out.append("        #if canImport(UIKit)")
    out.append("        self.init(uiColor: UIColor { traits in")
    out.append("            traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)")
    out.append("        })")
    out.append("        #elseif canImport(AppKit)")
    out.append("        self.init(nsColor: NSColor(name: nil) { appearance in")
    out.append("            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua")
    out.append("            return NSColor(isDark ? dark : light)")
    out.append("        })")
    out.append("        #else")
    out.append("        self = light")
    out.append("        #endif")
    out.append("    }")
    out.append("")
    out.append("    /// sRGB color from 0–255 channels (matches the source token exactly).")
    out.append("    static func srgb(_ r: Double, _ g: Double, _ b: Double) -> Color {")
    out.append("        Color(.sRGB, red: r, green: g, blue: b, opacity: 1)")
    out.append("    }")
    out.append("}")
    out.append("")

    # --- ThemeColors ---------------------------------------------------------
    out.append("public struct ThemeColors {")
    for name in colors:
        lr, lg, lb = comp(colors[name])
        if name in dark:
            dr, dg, db = comp(dark[name])
        else:
            dr, dg, db = lr, lg, lb
        out.append(f"    public let {_camel(name)} = Color(")
        out.append(f"        light: .srgb({lr:.3f}, {lg:.3f}, {lb:.3f}),")
        out.append(f"        dark:  .srgb({dr:.3f}, {dg:.3f}, {db:.3f}))")
    out.append("}")
    out.append("")

    # --- ThemeSpacing --------------------------------------------------------
    sp = [s for s in (_num(x) for x in (spacing or [])) if s is not None]
    if sp:
        names = ["xs", "sm", "md", "lg", "xl", "xxl", "xxxl"]
        out.append("public struct ThemeSpacing {")
        for i, v in enumerate(sp):
            nm = names[i] if i < len(names) else f"s{i}"
            out.append(f"    public let {nm}: CGFloat = {v}")
        out.append("}")
        out.append("")

    # --- ThemeRadius ---------------------------------------------------------
    rad_map = {}
    if rounded:
        for k, v in rounded.items():
            n = _num(v)
            if n is not None:
                rad_map[_camel(k)] = n
    elif radius:
        names = ["sm", "md", "lg", "pill"]
        for i, v in enumerate(radius):
            n = _num(v)
            if n is not None:
                rad_map[names[i] if i < len(names) else f"r{i}"] = n
    if rad_map:
        out.append("public struct ThemeRadius {")
        for nm, v in rad_map.items():
            out.append(f"    public let {nm}: CGFloat = {v}")
        out.append("}")
        out.append("")

    # --- Typography: a TextStyle spec carrying size/weight/lineHeight --------
    first_family = fonts[0] if fonts else None
    if typography:
        out.append("public struct TextStyleSpec {")
        out.append("    public let font: Font")
        out.append("    public let lineSpacing: CGFloat")
        out.append("    public let lineHeight: CGFloat")
        out.append("}")
        out.append("")
        out.append("public struct ThemeTypography {")
        for role, spec in typography.items():
            fam = spec.get("family") or first_family
            size = _num(spec.get("size")) or "16"
            weight = _swift_weight(spec.get("weight"))
            lh = _num(spec.get("line_height"))
            # lineSpacing = lineHeight - fontSize (SwiftUI adds spacing BETWEEN lines).
            ls = "0"
            if lh is not None:
                try:
                    ls = str(int(float(lh) - float(size)))
                except ValueError:
                    ls = "0"
            if fam:
                font_expr = f'.custom("{fam}", size: {size}).weight(.{weight})'
            else:
                font_expr = f'.system(size: {size}, weight: .{weight})'
            out.append(f"    public let {_camel(role)} = TextStyleSpec(")
            out.append(f"        font: {font_expr},")
            out.append(f"        lineSpacing: {ls},")
            out.append(f"        lineHeight: {lh if lh is not None else size})")
        out.append("}")
        out.append("")
        # A named text-style enum keyed to the typography roles, for ergonomic
        # `.textStyle(.title)` access. The KeyPath maps each case to its stored spec
        # on the live, in-environment ThemeTypography — so the named API reads the
        # SAME values the theme carries and can never drift, and does NOT rebuild a
        # fresh ThemeTypography per call.
        roles = list(typography.keys())
        out.append("public enum TextStyle: CaseIterable {")
        out.append("    case " + ", ".join(_camel(r) for r in roles))
        out.append("    /// KeyPath into ThemeTypography for this style.")
        out.append("    public var keyPath: KeyPath<ThemeTypography, TextStyleSpec> {")
        out.append("        switch self {")
        for r in roles:
            cm = _camel(r)
            out.append(f"        case .{cm}: return \\.{cm}")
        out.append("        }")
        out.append("    }")
        out.append("}")
        out.append("")
        # The .textStyle() view modifiers. The spec overload is a plain helper; the
        # named overload reads the in-environment theme so it stays in sync.
        out.append("public extension View {")
        out.append("    /// Apply a theme text style (font + line spacing) to a view.")
        out.append("    func textStyle(_ spec: TextStyleSpec) -> some View {")
        out.append("        self.font(spec.font).lineSpacing(spec.lineSpacing)")
        out.append("    }")
        out.append("")
        out.append("    /// Apply a NAMED theme text style, e.g. `.textStyle(.title)`.")
        out.append("    /// Resolves against the in-environment theme so it tracks any")
        out.append("    /// theme override rather than a hard-coded default.")
        out.append("    func textStyle(_ style: TextStyle) -> some View {")
        out.append("        modifier(NamedTextStyle(style: style))")
        out.append("    }")
        out.append("}")
        out.append("")
        out.append("private struct NamedTextStyle: ViewModifier {")
        out.append("    @Environment(\\.theme) private var theme")
        out.append("    let style: TextStyle")
        out.append("    func body(content: Content) -> some View {")
        out.append("        content.textStyle(theme.typography[keyPath: style.keyPath])")
        out.append("    }")
        out.append("}")
        out.append("")
    elif fonts:
        # No typography map: still expose a Font helper per family.
        out.append("public extension Font {")
        for i, f in enumerate(fonts):
            role = "display" if i == 0 else ("body" if i == 1 else _camel(f))
            out.append(f'    static func {role}(_ size: CGFloat) -> Font {{ .custom("{f}", size: size) }}')
        out.append("}")
        out.append("")

    # --- Theme value + Environment integration -------------------------------
    out.append("public struct Theme {")
    out.append("    public let colors = ThemeColors()")
    if sp:
        out.append("    public let spacing = ThemeSpacing()")
    if rad_map:
        out.append("    public let radius = ThemeRadius()")
    if typography:
        out.append("    public let typography = ThemeTypography()")
    out.append("    public init() {}")
    out.append("}")
    out.append("")
    out.append("private struct ThemeKey: EnvironmentKey {")
    out.append("    static let defaultValue = Theme()")
    out.append("}")
    out.append("")
    out.append("public extension EnvironmentValues {")
    out.append("    var theme: Theme {")
    out.append("        get { self[ThemeKey.self] }")
    out.append("        set { self[ThemeKey.self] = newValue }")
    out.append("    }")
    out.append("}")
    out.append("")

    # --- Shadow helper (honest approximation of the CSS elevation token) ------
    if shadows:
        out.append("public extension View {")
        out.append("    /// Card elevation — a single-layer approximation of the contract's")
        out.append("    /// multi-layer CSS box-shadow (SwiftUI shadows are single-layer).")
        out.append("    func cardShadow() -> some View {")
        out.append("        self.shadow(color: .black.opacity(0.10), radius: 3, x: 0, y: 1)")
        out.append("    }")
        out.append("}")
        out.append("")

    # --- Usage example -------------------------------------------------------
    out.append("// MARK: - Usage")
    out.append("struct ThemedCard: View {")
    out.append("    @Environment(\\.theme) private var theme")
    out.append("    var body: some View {")
    style = "headline" if "headline" in typography else (
        _camel(next(iter(typography))) if typography else None)
    pad = "theme.spacing.lg" if sp else "16"
    rad = "theme.radius.md" if "md" in rad_map else (
        f"theme.radius.{next(iter(rad_map))}" if rad_map else "10")
    out.append("        VStack(alignment: .leading, spacing: " + (("theme.spacing.sm" if sp else "8")) + ") {")
    if style:
        out.append(f'            Text("Aurora").textStyle(.{style})  // named, reads @Environment theme')
    else:
        out.append('            Text("Aurora")')
    out.append("                .foregroundStyle(theme.colors.text)")
    out.append(f"        }}")
    out.append(f"        .padding({pad})")
    out.append("        .background(theme.colors.surface)")
    out.append(f"        .clipShape(RoundedRectangle(cornerRadius: {rad}, style: .continuous))")
    out.append("        .overlay(")
    out.append(f"            RoundedRectangle(cornerRadius: {rad}, style: .continuous)")
    out.append("                .stroke(theme.colors.border, lineWidth: 1))")
    if shadows:
        out.append("        .cardShadow()")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("// Inject the theme once near the root; descendants read @Environment(\\.theme).")
    out.append("// Swap in a different Theme() here (or per preview) to retheme the subtree.")
    out.append("struct ThemedRoot: View {")
    out.append("    var body: some View {")
    out.append("        ThemedCard()")
    out.append("            .padding()")
    out.append("            .background(Theme().colors.background)")
    out.append("            .environment(\\.theme, Theme())")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#if DEBUG")
    out.append('#Preview("Light") { ThemedRoot().preferredColorScheme(.light) }')
    out.append('#Preview("Dark")  { ThemedRoot().preferredColorScheme(.dark) }')
    out.append("#endif")

    return "\n".join(out) + "\n"


def flutter(colors, fonts):
    lines = ["import 'package:flutter/material.dart';", "",
             "// Generated by atelier from the design contract. Do not edit by hand.",
             "class AppColors {"]
    for name, hexv in colors.items():
        r, g, b = _hex_to_rgb(hexv)
        lines.append(f"  static const {_camel(name)} = Color(0xFF{r:02X}{g:02X}{b:02X});")
    lines.append("}")
    if fonts:
        lines += ["", "class AppFonts {",
                  f"  static const String display = '{fonts[0]}';"]
        if len(fonts) > 1:
            lines.append(f"  static const String body = '{fonts[1]}';")
        lines.append("}")
    return "\n".join(lines) + "\n"


def react_native(colors, fonts):
    cols = ",\n".join(f'    {_camel(n)}: "{h}"' for n, h in colors.items())
    fnt = ",\n".join(f'    {("display" if i==0 else "body" if i==1 else _camel(f))}: "{f}"'
                     for i, f in enumerate(fonts))
    return ("// Generated by atelier from the design contract. Do not edit by hand.\n"
            "export const theme = {\n"
            f"  colors: {{\n{cols}\n  }},\n"
            f"  fonts: {{\n{fnt}\n  }},\n"
            "} as const;\n")


def write_all(colors, fonts, out_dir, dark=None, typography=None, spacing=None,
              radius=None, rounded=None, shadows=None):
    os.makedirs(out_dir, exist_ok=True)
    files = {"Theme.swift": swiftui(colors, fonts, dark=dark, typography=typography,
                                    spacing=spacing, radius=radius, rounded=rounded,
                                    shadows=shadows),
             "app_colors.dart": flutter(colors, fonts),
             "theme.native.ts": react_native(colors, fonts)}
    for fn, content in files.items():
        with open(os.path.join(out_dir, fn), "w", encoding="utf-8") as fh:
            fh.write(content)
    return [os.path.join(out_dir, fn) for fn in files]


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a]
    if not args or args[0].startswith("-"):
        print("usage: export_native.py <repo | design-tokens.json> [--out design/native]")
        sys.exit(2)
    c = resolve_contract(args[0])
    colors = {n: v for n, v in c["colors"].items() if isinstance(v, str) and v.startswith("#")}
    dark = {n: v for n, v in (c.get("dark_colors") or {}).items()
            if isinstance(v, str) and v.startswith("#")}
    out = args[args.index("--out") + 1] if "--out" in args else "design/native"
    written = write_all(colors, c["fonts"], out, dark=dark,
                        typography=c.get("typography"), spacing=c.get("spacing"),
                        radius=c.get("radius"), rounded=c.get("rounded"),
                        shadows=c.get("shadows"))
    print("Wrote " + ", ".join(written))
