"""Generate native theme code from the design tokens — real cross-platform handoff.

Beyond CSS/Tailwind/W3C-JSON, this emits the platform-idiomatic theme files so the
SAME contract drives SwiftUI, Flutter, and React Native — not just "export the JSON
and figure it out". The canonical source stays `design-tokens.json` / DESIGN.md.

Usage:
    python3 export_native.py <repo | design-tokens.json> [--out design/native]
"""
import os
import sys

from contract import resolve_contract
from scan_repo import _hex_to_rgb


def _pascal(name):
    return "".join(p.capitalize() for p in name.replace("-", " ").replace("_", " ").split())


def _camel(name):
    p = _pascal(name)
    return p[:1].lower() + p[1:] if p else name


def swiftui(colors, fonts):
    lines = ["import SwiftUI", "",
             "// Generated by atelier from the design contract. Do not edit by hand.",
             "extension Color {"]
    for name, hexv in colors.items():
        r, g, b = _hex_to_rgb(hexv)
        lines.append(f"    static let {_camel(name)} = Color(red: {r/255:.3f}, "
                     f"green: {g/255:.3f}, blue: {b/255:.3f})")
    lines.append("}")
    if fonts:
        lines += ["", "extension Font {"]
        for i, f in enumerate(fonts):
            role = "display" if i == 0 else ("body" if i == 1 else _camel(f))
            lines.append(f'    static func {role}(_ size: CGFloat) -> Font {{ .custom("{f}", size: size) }}')
        lines.append("}")
    return "\n".join(lines) + "\n"


def flutter(colors, fonts):
    lines = ["import 'package:flutter/material.dart';", "",
             "// Generated by atelier from the design contract. Do not edit by hand.",
             "class AppColors {"]
    for name, hexv in colors.items():
        r, g, b = _hex_to_rgb(hexv)
        lines.append(f"  static const {_camel(name)} = Color(0xFF{r:02X}{g:02X}{b:02X});")
    lines.append("}")
    if fonts:
        lines += ["", "class AppFonts {",
                  f"  static const String display = '{fonts[0]}';"]
        if len(fonts) > 1:
            lines.append(f"  static const String body = '{fonts[1]}';")
        lines.append("}")
    return "\n".join(lines) + "\n"


def react_native(colors, fonts):
    cols = ",\n".join(f'    {_camel(n)}: "{h}"' for n, h in colors.items())
    fnt = ",\n".join(f'    {("display" if i==0 else "body" if i==1 else _camel(f))}: "{f}"'
                     for i, f in enumerate(fonts))
    return ("// Generated by atelier from the design contract. Do not edit by hand.\n"
            "export const theme = {\n"
            f"  colors: {{\n{cols}\n  }},\n"
            f"  fonts: {{\n{fnt}\n  }},\n"
            "} as const;\n")


def write_all(colors, fonts, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    files = {"AppColors.swift": swiftui(colors, fonts),
             "app_colors.dart": flutter(colors, fonts),
             "theme.native.ts": react_native(colors, fonts)}
    for fn, content in files.items():
        with open(os.path.join(out_dir, fn), "w", encoding="utf-8") as fh:
            fh.write(content)
    return [os.path.join(out_dir, fn) for fn in files]


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a]
    if not args or args[0].startswith("-"):
        print("usage: export_native.py <repo | design-tokens.json> [--out design/native]")
        sys.exit(2)
    c = resolve_contract(args[0])
    colors = {n: v for n, v in c["colors"].items() if isinstance(v, str) and v.startswith("#")}
    out = args[args.index("--out") + 1] if "--out" in args else "design/native"
    written = write_all(colors, c["fonts"], out)
    print("Wrote " + ", ".join(written))
